# Generated by Django 5.1.4 on 2026-08-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0003_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
